#!/usr/bin/env perl

use DBIx::Class::Schema::Loader 'make_schema_at';

my $DEBUG = @ARGV and $ARGV[0] =~ /^\-[\-]*v/;

say $DBIx::Class::Schema::Loader::VERSION if $DEBUG;
my @dsn = 'dbi:SQLite:dbname=users.db';

my $options = {
  debug          => $DEBUG,
  dump_directory => 'lib',
  components     => [qw/ InflateColumn::DateTime /],
  generate_pod   => 0,
};

make_schema_at(Schema => $options, \@dsn);

=head1 NAME

generate_schema

Genera las clases de los modelos.

=head1 USAGE

perl generate_schema

=cut

